remote_theme: "mmistakes/minimal-mistakes@4.24.0"
lsi: false
safe: true
source: /docs
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: Interpreting Open-AI's Whisper
plugins:
  - jekyll-include-cache
