remote-theme: minimal-mistakes-jekyll
lsi: false
safe: true
source: /docs
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: Interpreting Open-AI's Whisper
